export const types = {
    openCreateUserModal: '[ui] Open create user modal',
    closeCreateUserModal: '[ui] Close create user modal',
    openEditUserModal: '[ui] Open edit user modal',
    closeEditUserModal: '[ui] Close edit user modal',
    openDeleteUserDialog: '[ui] Open delete user dialog',
    closeDeleteUserDialog: '[ui] Close delete user dialog',

    openCreateProductModal: '[ui] Open create product modal',
    closeCreateProductModal: '[ui] Close create product modal',
    openEditProductModal: '[ui] Open edit product modal',
    closeEditProductModal: '[ui] Close edit product modal',
    openDeleteProductDialog: '[ui] Open delete product dialog',
    closeDeleteProductDialog: '[ui] Close delete product dialog',

    startLoading: '[Auth] Start loading',
    login: '[Auth] Login',
    logout: '[Auth] Logout',
    errorFound: '[Auth] Error found',

    setActiveUser: '[Users] Set active user',
    usersLoaded: '[Users] Users loaded',
    userCreated: '[Users] User created',
    userUpdated: '[Users] User updated',
    userDeleted: '[Users] User deleted',
    startLoadingUser: '[Users] Start loading user',
    errorFoundUser: '[Users] Error found user',

    setSelectedProduct: '[Products] Set active user',
    productsLoaded: '[Products] Products loaded',
    productCreated: '[Products] User created',
    productUpdated: '[Products] User updated',
    productDeleted: '[Products] User deleted',
    startLoadingProducts: '[Products] Start loading user',
    stopLoadingProducts: '[Products] Stop loading user',
}